package meka.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * Displays a speaker avatar beside one chat message.
 */
public class DialogBox extends HBox {
    private static final Image USER_IMAGE = new Image(
            DialogBox.class.getResourceAsStream("/images/dva.jpg"));

    private static final Image MEKA_IMAGE = new Image(
            DialogBox.class.getResourceAsStream("/images/dmon.jpg"));

    @FXML
    private Label dialog;

    @FXML
    private ImageView avatar;

    private DialogBox(String text) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load the dialog box view.", exception);
        }
        dialog.setText(text);
    }

    /**
     * Returns a right-aligned dialog for a message entered by the user.
     *
     * @param text message to display.
     * @return user dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text);
        dialogBox.avatar.setImage(USER_IMAGE);
        dialogBox.getStyleClass().add("user-dialog");
        return dialogBox;
    }

    /**
     * Returns a left-aligned dialog for a response generated by MEKA.
     *
     * @param text message to display.
     * @return MEKA dialog box.
     */
    public static DialogBox getMekaDialog(String text) {
        DialogBox dialogBox = new DialogBox(text);
        dialogBox.avatar.setImage(MEKA_IMAGE);
        dialogBox.flip();
        dialogBox.getStyleClass().add("meka-dialog");
        return dialogBox;
    }

    /**
     * Places the avatar on the left and message on the right for MEKA replies.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
    }
}
